### ISSUE TITLE
https://www.51zhibo.top 无法访问了

### ISSUE THREAD

**Issue by ycyranqingjjs** [DOUBLE-Baller/WebRTC_IM#2]
https://www.51zhibo.top 无法访问了，微信群已经无法加入了

**Comment by tlzb** [comment]
骗子一个千万别加他微信QQ和群，我被骗了，大家千万别上当
他全名叫：杨松、QQ号：779763764：微信号：BCFind5 qq群:274904994
支付宝：185开头的02结尾。说帮您搞，其实是随便乱改，扔给你就不管了。可以百度他资料有人举报过！

**Comment by qmcloud** [comment]
域名到期
